### ISSUE TITLE
ScaleType

### ISSUE THREAD

**Issue by Aleatoire** [mallethugo/RealParallaxAndroid#3]
Hello, how can i force an image to fit fullscreen height's size ?

Thx ;)

**Comment by mallethugo** [comment]
The scale type is set to center into the library. You don't need to override it if your picture has the good size.

Look the demo sample if you need fullscreen. You can paste your code too and I would be very happy to help you.

It's my first library and it's not be perfect so we can improve it with you use case maybe.
